---
- name: create users accounts for all our servers
  hosts: labservers
  become: true
  remote_user: jthaem
  vars_files:
    - secret.yml
  tasks:
    - name: createing users from secret.yml
      user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items: "{{ newusers }}"

