---
- name: Install apache and starts the service
  hosts: labservers
  become: yes
  tasks:
  - name: Install the required package
    yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: latest
  - name: start the service
    service:
        name: "{{ ansible_local.custom.general.service }}"
        state: "{{ ansible_local.custom.general.state }}"
...

